# Generated by Django 4.2.7 on 2023-12-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Categorie',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
